<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="manifest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="application" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="version" type="xs:string"/>
              <xs:element name="permission" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="products" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="product" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>
